//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: Telegram
// UUID: 6DF1F171-B680-CD87-E9E7-36108C3E592D
//
//                           Arch: arm64
//                 Source version: 0.0.0.0.0
//            Minimum iOS version: 9.0.0
//                    SDK version: 13.2.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = /Frameworks
//                       Run path: @loader_path/Frameworks
//                               = /Frameworks
//                       Run path: /var/containers/Bundle/Application/3BC18C93-1ED6-471A-B089-693F02902536/Telegram.app/Frameworks
//                               = /var/containers/Bundle/Application/3BC18C93-1ED6-471A-B089-693F02902536/Telegram.app/Frameworks
//         This file is encrypted:
//                                   cryptid: 0x00000001
//                                  cryptoff: 0x00007000
//                                 cryptsize: 0x00001000
//

